(() => {
  'use strict';
  const cfg=window.ACCOUNT_HUB_CONFIG||{},API=(cfg.CUBE_CLUB_API_URL||'').replace(/\/$/,'');
  const local=['localhost','127.0.0.1'].includes(location.hostname),demoOn=Boolean(cfg.DEMO_MODE&&local);
  const clubURL=cfg.CUBE_CLUB_SITE_URL||'#';
  const demo={account:{id:'demo-account',display_name:'CubeNinja',email:'ninja@example.test',points:4250,rank:7,best_single:24.83,best_average:29.72,total_solves:1284,completed_goals:8,achievements_count:17},tokens:[],transactions:[{description:'Completed 50 solves',amount:100,created_at:'2026-09-30'},{description:'Reached Sub-30',amount:250,created_at:'2026-09-28'}],solves:[],goals:[]};
  let session=null,account=null,cache={},notice=''; const app=document.getElementById('app');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>Number(n||0).toLocaleString();
  const date=v=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
  const route=()=>location.hash.replace(/^#\/?/,'').split('/')[0]||'login';
  function go(r){location.hash='#/'+r;}
  function fail(msg){let e=new Error(msg);throw e;}
  async function api(path,opts={}){
    if(demoOn&&!API)return demoApi(path,opts);
    if(!API)fail('Account Hub API is not configured. Set CUBE_CLUB_API_URL in config.js.');
    const headers={...(opts.headers||{})};if(!(opts.body instanceof FormData)&&opts.body!==undefined)headers['Content-Type']='application/json';if(session?.token)headers.Authorization=`Bearer ${session.token}`;
    let res;try{res=await fetch(API+path,{...opts,headers,credentials:'include'});}catch{fail('Cannot reach the backend. Check its URL, HTTPS, and CORS settings.');}
    let body=await res.json().catch(()=>({}));if(!res.ok){let map={INVALID_CREDENTIALS:'Email or password was not accepted.',TOKEN_EXPIRED:'That token has expired.',TOKEN_REVOKED:'That token has been revoked.'};fail(map[body.code]||body.message||`Request failed (${res.status}).`);}return body;
  }
  async function demoApi(path,opts){if(path==='/auth/register'||path==='/auth/login')return {account:demo.account,session_token:'LOCAL_DEMO_SESSION'};if(path==='/auth/logout')return {};if(path==='/account')return {account:demo.account};if(path==='/account/stats')return {stats:demo.account};if(path==='/account/tokens'&&opts.method==='POST'){let t={id:crypto.randomUUID(),created_at:new Date().toISOString(),expires_at:new Date(Date.now()+7*86400000).toISOString(),revoked_at:null};demo.tokens.unshift(t);return {token:{...t,secret:'CC-DEMO-ONLY-DO-NOT-USE'}};}if(path==='/account/tokens'&&opts.method==='GET')return {tokens:demo.tokens};if(path.startsWith('/account/tokens/')&&opts.method==='DELETE'){let id=path.split('/').pop(),t=demo.tokens.find(x=>x.id===id);if(t)t.revoked_at=new Date().toISOString();return {};}if(path==='/account/transactions')return {transactions:demo.transactions};if(path==='/account/goals')return {goals:demo.goals};if(path==='/account/solves')return {solves:demo.solves};if(path==='/account/imports/cstimer')return {import:{accepted:0,duplicates:0,flagged:0,review_status:'DEMO'}};return {};}
  function brand(){return `<div class="brand"><div class="mark">✦</div><div>CUBE CLUB<small>ACCOUNT HUB</small></div></div>`;}
  function status(){return notice?`<div class="notice ${notice.startsWith('Error:')?'error':'success'}">${esc(notice.replace(/^Error: ?/,''))}</div>`:'';}
  function authPage(register=false){return `<div class="auth-wrap"><section class="form-card">${brand()}<h1>${register?'Create your account':'Welcome back'}</h1><p class="sub">${register?'Start tracking solves and earning club points.':'Sign in to manage your Cube Club account.'}</p>${status()}<form id="auth-form"><div class="field"><label>Email</label><input required name="email" type="email" autocomplete="email" placeholder="you@example.com"></div>${register?'<div class="field"><label>Display name</label><input required name="display_name" maxlength="32" autocomplete="nickname" placeholder="CubeNinja"></div>':''}<div class="field"><label>Password</label><input required name="password" type="password" minlength="10" autocomplete="current-password" placeholder="At least 10 characters"></div><button class="btn full" type="submit">${register?'CREATE ACCOUNT':'SIGN IN'} <span>↗</span></button></form><div class="form-links"><a href="#/${register?'login':'register'}">${register?'Already have an account? Sign in':'Create an Account'}</a><a href="${esc(clubURL)}">Cube Club website ↗</a></div>${demoOn?'<div class="notice success">Local demo mode. Use any email and password; demo data is not persistent.</div>':''}<div class="notice">Your account and solve records live on the secure backend. The Cube Club website uses a separate expiring token to authenticate you.</div></section></div>`;}
  const items=[['dashboard','▦','OVERVIEW'],['solves','⏱','SOLVES'],['goals','◎','GOALS & STATS'],['points','🧊','POINTS'],['tokens','🔑','TOKENS'],['settings','⚙','ACCOUNT']];
  function shell(r,html){return `<div class="shell"><aside class="sidebar">${brand()}<nav class="nav">${items.map(([k,i,l])=>`<a href="#/${k}" class="${k===r?'active':''}">${i} &nbsp; ${l}</a>`).join('')}</nav><div class="side-bottom"><div class="side-card"><span class="eyebrow">SIGNED IN AS</span><p><b>${esc(account?.display_name||account?.email||'Member')}</b><br>${esc(account?.email||'')}</p></div><button class="quiet-btn" data-action="logout">↪ &nbsp; Sign out</button></div></aside><main class="main"><header class="topbar"><div class="crumb">ACCOUNT HUB / ${esc(r)}</div><div class="tools"><button class="icon-btn" data-action="theme" aria-label="Toggle theme">◐</button><span>${esc(account?.display_name||'Member')}</span><div class="avatar">${esc((account?.display_name||'M')[0].toUpperCase())}</div></div></header>${html}<div class="footer">Cube Club Account Hub · Your account data stays on the backend · <a class="text-link" href="${esc(clubURL)}">Go to Cube Club ↗</a></div></main><nav class="mobile-nav">${items.map(([k,i,l])=>`<a href="#/${k}" class="${k===r?'active':''}"><span>${i}</span>${l.split(' ')[0]}</a>`).join('')}</nav></div>`;}
  const stat=(label,value,icon,sub='Verified account data')=>`<article class="card"><div class="stat-label">${label} <span>${icon}</span></div><div class="stat-value">${value}</div><div class="stat-foot">${sub}</div></article>`;
  function dashboard(){let a=cache['/account/stats']?.stats||account||{},transactions=cache['/account/transactions']?.transactions||[];return `${status()}<section class="hero"><span class="eyebrow">YOUR SPEEDCUBING JOURNEY</span><h1>Hey, ${esc(a.display_name||'solver')}! 👋</h1><p>Your account is the home of your solve history, verified progress, Cube Points, and login tokens for the main club site.</p><a class="btn" href="#/tokens">Manage Cube Club tokens →</a></section><div class="grid stats">${stat('CUBE POINTS',`${fmt(a.points??a.cube_points)} CP`,'🧊')}${stat('CLUB RANK',`#${fmt(a.rank)}`,'🏆')}${stat('BEST SINGLE',`${a.best_single??'—'}s`,'⚡')}${stat('BEST AVERAGE',`${a.best_average??'—'}s`,'📊')}${stat('TOTAL SOLVES',fmt(a.total_solves),'🎯')}${stat('GOALS COMPLETED',fmt(a.completed_goals),'◎')}${stat('ACHIEVEMENTS',fmt(a.achievements_count),'🏅')}${stat('ACCOUNT',a.disabled_at?'DISABLED':'ACTIVE','🔐','Account status from server')}</div><div class="grid columns"><section class="card"><div class="section-head"><h2>Recent Cube Points</h2><a class="text-link" href="#/points">History →</a></div><div class="activity-list">${transactions.length?transactions.slice(0,5).map(t=>`<div class="activity"><div class="activity-icon">✦</div><div class="activity-copy"><b>${esc(t.description||t.reason)}</b><small>${date(t.created_at)}</small></div><span class="amount">${Number(t.amount)>0?'+':''}${fmt(t.amount)} CP</span></div>`).join(''):'<div class="empty">Points transactions from verified activity will appear here.</div>'}</div></section><section class="card"><h2>Import solves from CSTimer</h2><p class="muted">Export your solves from CSTimer, then upload the export for server-side validation. Cube Club does not access CSTimer accounts directly.</p><a class="btn secondary" href="#/solves">Import a solve file ↗</a></section></div>`;}
  function solves(){let rows=cache['/account/solves']?.solves||[];return `<h1 class="page-title">Solve history ⏱</h1><p class="sub">Import exported CSTimer solve files. The backend validates, deduplicates, and calculates statistics.</p>${status()}<div class="grid columns"><section class="card"><div class="section-head"><h2>Import solve export</h2><span class="badge">CSTIMER FILE</span></div><form id="import-form"><div class="field"><label for="solve-file">Export file (.txt, .csv, .json)</label><input id="solve-file" type="file" name="file" accept=".txt,.csv,.json,text/plain,text/csv,application/json" required></div><p class="muted">Use CSTimer’s export feature. No direct account access is claimed. The server validates solve formats, flags unusual times, and prevents repeated imports from earning duplicate points.</p><button class="btn" type="submit">UPLOAD FOR VALIDATION ↗</button></form><div id="import-result"></div></section><section class="card"><h2>Import results</h2><p class="muted">Accepted solves may update stats and goal progress after backend verification. Suspicious activity is flagged for club review.</p></section></div><h2 style="margin-top:25px">Recent solves</h2><div class="table-wrap"><table><thead><tr><th>Solve time</th><th>Scramble</th><th>Solved at</th><th>Review</th></tr></thead><tbody>${rows.length?rows.map(s=>`<tr><td><b>${(Number(s.duration_ms)/1000).toFixed(2)}s</b></td><td>${esc(s.scramble||'—')}</td><td>${date(s.solved_at)}</td><td><span class="badge ${s.review_status==='flagged'?'warn':'done'}">${esc(s.review_status||'accepted')}</span></td></tr>`).join(''):'<tr><td colspan="4" class="empty">No imported solves yet.</td></tr>'}</tbody></table></div>`;}
  function tokens(){let rows=cache['/account/tokens']?.tokens||[];return `<h1 class="page-title">Cube Club tokens 🔑</h1><p class="sub">Create an expiring login credential for the separate Cube Club website.</p>${status()}<section class="card"><div class="section-head"><h2>Generate a token</h2><span class="badge">CREDENTIAL ONLY</span></div><p class="muted">A token authenticates you; it contains no Cube Points, profile data, solve times, or expiration details. The raw token is shown once. The backend stores a secure hash, expiry, revoke state, and last-used time.</p><form id="token-form"><div class="field"><label for="expiry">Token lifetime</label><select id="expiry" name="expires_in_days"><option value="1">24 hours</option><option value="7" selected>7 days</option><option value="30">30 days</option></select></div><button class="btn" type="submit">GENERATE TOKEN ↗</button></form><div id="new-token"></div></section><section class="card" style="margin-top:16px"><div class="section-head"><h2>Active and past tokens</h2><button class="btn secondary" data-action="refresh-tokens">Refresh</button></div><p class="muted">Revoke a token immediately if you no longer need it or think it was exposed.</p><div class="table-wrap"><table><thead><tr><th>Created</th><th>Expires</th><th>Last used</th><th>Status</th><th></th></tr></thead><tbody>${rows.length?rows.map(t=>`<tr><td>${date(t.created_at)}</td><td>${date(t.expires_at)}</td><td>${date(t.last_used_at)}</td><td><span class="badge ${t.revoked_at?'warn':'done'}">${t.revoked_at?'REVOKED':new Date(t.expires_at)<new Date()?'EXPIRED':'ACTIVE'}</span></td><td>${!t.revoked_at&&new Date(t.expires_at)>new Date()?`<button class="btn danger" data-revoke="${esc(t.id)}">Revoke</button>`:''}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No tokens created yet.</td></tr>'}</tbody></table></div></section><div class="notice">If a token expires or is revoked, use the Cube Club Account Hub to generate a new one. The server clock decides expiration.</div>`;}
  function goals(){let gs=cache['/account/goals']?.goals||[];return `<h1 class="page-title">Your goals & stats 🎯</h1><p class="sub">The backend compares goals to validated solve history and awards points once when earned.</p>${status()}<div class="grid two">${gs.map(g=>`<article class="card"><div class="section-head"><h2>${esc(g.name)}</h2><span class="badge ${g.state==='COMPLETED'?'done':g.state==='LOCKED'?'warn':''}">${esc(g.state||'IN PROGRESS')}</span></div><p class="muted">${esc(g.description||'Club milestone')} · Reward ${fmt(g.reward_points)} CP</p>${g.state==='IN PROGRESS'?`<div class="muted">Progress: ${fmt(g.progress)} / ${fmt(g.target)}</div><div style="height:7px;background:var(--line);border-radius:99px;margin-top:8px;overflow:hidden"><i style="display:block;height:100%;width:${Math.min(100,Number(g.progress_percent)||0)}%;background:linear-gradient(90deg,var(--cyan),var(--lime))"></i></div>`:''}</article>`).join('')||'<div class="card empty">Goals published by the club will appear here.</div>'}</div><div class="notice">Goal completion is never claimed by the browser. The API verifies qualifying solve data and prevents repeat awards.</div>`;}
  function points(){let rows=cache['/account/transactions']?.transactions||[];return `<h1 class="page-title">Cube Points 🧊</h1><p class="sub">Your balance is backed by the trusted points ledger.</p>${status()}<div class="hero"><span class="eyebrow">CURRENT BALANCE</span><h1>${fmt(account?.points)} CP</h1><p>Only verified backend activity changes your balance.</p></div><div class="table-wrap"><table><thead><tr><th>Activity</th><th>Amount</th><th>Date</th><th>Reference</th></tr></thead><tbody>${rows.length?rows.map(t=>`<tr><td><b>${esc(t.description||t.reason)}</b></td><td class="amount">${Number(t.amount)>0?'+':''}${fmt(t.amount)} CP</td><td>${date(t.created_at)}</td><td>${esc(t.source_type||'—')}</td></tr>`).join(''):'<tr><td colspan="4" class="empty">Your verified points transactions will appear here.</td></tr>'}</tbody></table></div>`;}
  function settings(){return `<h1 class="page-title">Account settings ⚙</h1><p class="sub">Manage your Cube Club Account Hub sign-in and privacy options.</p>${status()}<section class="card"><h2>Account</h2><p>Email: <b>${esc(account?.email||'')}</b></p><p>Display name: <b>${esc(account?.display_name||'')}</b></p><p class="muted">Changing password, email, and public-stat visibility must be completed through the authenticated backend/Account Hub settings API.</p><form id="password-form"><div class="field"><label>Current password</label><input name="current_password" type="password" autocomplete="current-password" required></div><div class="field"><label>New password</label><input name="new_password" type="password" minlength="10" autocomplete="new-password" required></div><button class="btn secondary" type="submit">UPDATE PASSWORD</button></form></section><section class="card" style="margin-top:16px"><h2>Privacy controls</h2><p class="muted">Choose which statistics are public on Cube Club member profiles. Your email, account ID, and tokens are always private.</p><form id="privacy-form" class="grid columns">${[['points','Cube Points'],['best_single','Best Single'],['best_average','Best Average'],['total_solves','Total Solves'],['achievements','Achievements']].map(([k,label])=>`<label><input type="checkbox" name="${k}" ${account?.profile_visibility?.[k]!==false?'checked':''}> ${label}</label>`).join('')}<button class="btn secondary" type="submit">SAVE PROFILE PRIVACY</button></form></section>`;}
  async function load(r){let paths={dashboard:['/account','/account/stats','/account/transactions'],solves:['/account/solves'],goals:['/account/goals'],points:['/account/transactions'],tokens:['/account/tokens'],settings:['/account']};for(const p of paths[r]||[]){try{let x=await api(p);cache[p]=x;if(p==='/account'&&x.account)account={...account,...x.account};}catch(e){cache[p]={error:e.message};notice='Error: '+e.message;}}}
  function render(){let r=route();if(r==='login'||r==='register')return app.innerHTML=authPage(r==='register');if(!account)return app.innerHTML=authPage(false);let views={dashboard,solves,goals,points,tokens,settings};app.innerHTML=shell(r,(views[r]||dashboard)());}
  async function refresh(){notice='';let r=route();if(account)await load(r);render();}
  app.addEventListener('submit',async e=>{e.preventDefault();notice='';let f=e.target;
    try{
      if(f.id==='auth-form'){const fd=new FormData(f),register=route()==='register',payload=Object.fromEntries(fd.entries());const result=await api(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(payload)});account=result.account||result.user;session={token:result.session_token};if(result.session_token)sessionStorage.setItem('accountHubSession',result.session_token);if(!demoOn){let me=await api('/account');account={...account,...(me.account||me)};}go('dashboard');}
      if(f.id==='token-form'){let out=await api('/account/tokens',{method:'POST',body:JSON.stringify({expires_in_days:Number(new FormData(f).get('expires_in_days'))})});let issued=out.token||out;let box=document.getElementById('new-token');box.innerHTML=`<div class="tokenbox"><b>Copy this token now. It will not be shown again.</b><p><code>${esc(issued.secret||issued.token)}</code></p><div class="muted">Expires ${date(issued.expires_at)} · Keep it private; anyone holding it may sign in until it expires or is revoked.</div></div>`;notice='Token created. Copy it before leaving this page.';await load('tokens');render();document.getElementById('new-token').innerHTML=box.innerHTML;}
      if(f.id==='import-form'){const file=new FormData(f).get('file');if(!file||!file.size)fail('Select an export file first.');const body=new FormData();body.append('file',file);const out=await api('/account/imports/cstimer',{method:'POST',body});notice=`Import reviewed: ${fmt(out.import?.accepted)} accepted, ${fmt(out.import?.duplicates)} duplicates, ${fmt(out.import?.flagged)} flagged.`;await load('solves');render();}
      if(f.id==='password-form'){const payload=Object.fromEntries(new FormData(f).entries());await api('/account/password',{method:'POST',body:JSON.stringify(payload)});notice='Password updated.';render();}
      if(f.id==='privacy-form'){const fd=new FormData(f),profile_visibility={};for(const k of ['points','best_single','best_average','total_solves','achievements'])profile_visibility[k]=fd.has(k);await api('/account/profile-visibility',{method:'PATCH',body:JSON.stringify({profile_visibility})});account.profile_visibility=profile_visibility;notice='Profile visibility saved.';render();}
    }catch(err){notice='Error: '+err.message;render();}
  });
  app.addEventListener('click',async e=>{let action=e.target.closest('[data-action]')?.dataset.action;if(action==='theme'){document.body.classList.toggle('light');localStorage.setItem('hub-theme',document.body.classList.contains('light')?'light':'dark');return;}if(action==='logout'){try{await api('/auth/logout',{method:'POST',body:'{}'});}catch{}account=null;session=null;sessionStorage.removeItem('accountHubSession');go('login');render();return;}if(action==='refresh-tokens'){await load('tokens');render();return;}let revoke=e.target.closest('[data-revoke]');if(revoke){if(!confirm('Revoke this token now? Anyone using it will lose access.'))return;try{await api(`/account/tokens/${encodeURIComponent(revoke.dataset.revoke)}`,{method:'DELETE'});notice='Token revoked.';await load('tokens');render();}catch(err){notice='Error: '+err.message;render();}}});
  window.addEventListener('hashchange',refresh);if(localStorage.getItem('hub-theme')==='light')document.body.classList.add('light');
  session={token:sessionStorage.getItem('accountHubSession')};if(API){api('/account').then(x=>{account=x.account||x;refresh();}).catch(()=>{session=null;sessionStorage.removeItem('accountHubSession');render();});}else render();
})();
